setwd("/home/ross/workspace/mygithub/genbank-plants/allinone/cleaning")
#install.packages("Taxonstand")
library(Taxonstand)
yy <- read.csv("xaa",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxaa.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xab",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxab.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xac",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxac.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xad",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxad.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xae",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxae.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xaf",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxaf.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xag",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxag.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xah",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxah.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xai",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxai.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xaj",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxaj.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xak",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxak.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xal",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxal.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xam",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxam.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xan",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxan.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xao",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxao.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xap",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxap.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xaq",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxaq.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xar",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxar.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xas",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxas.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xat",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxat.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xau",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxau.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xav",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxav.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xaw",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxaw.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xax",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxax.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xay",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxay.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xaz",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxaz.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xba",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxba.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbb",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbb.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbc",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbc.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbd",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbd.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbe",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbe.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbf",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbf.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbg",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbg.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbh",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbh.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbi",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbi.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbj",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbj.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbk",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbk.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbl",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbl.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbm",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbm.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbn",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbn.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbo",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbo.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbp",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbp.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbq",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbq.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbr",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbr.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbs",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbs.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbt",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbt.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbu",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbu.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbv",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbv.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbw",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbw.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbx",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbx.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xby",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxby.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xbz",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxbz.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xca",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxca.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcb",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcb.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcc",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcc.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcd",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcd.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xce",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxce.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcf",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcf.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcg",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcg.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xch",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxch.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xci",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxci.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcj",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcj.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xck",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxck.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcl",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcl.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcm",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcm.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcn",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcn.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xco",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxco.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcp",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcp.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcq",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcq.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcr",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcr.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcs",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcs.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xct",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxct.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcu",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcu.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcv",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcv.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcw",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcw.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcx",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcx.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcy",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcy.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xcz",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxcz.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xda",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxda.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdb",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdb.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdc",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdc.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdd",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdd.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xde",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxde.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdf",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdf.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdg",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdg.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdh",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdh.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdi",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdi.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdj",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdj.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdk",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdk.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdl",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdl.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdm",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdm.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdn",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdn.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdo",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdo.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdp",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdp.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdq",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdq.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdr",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdr.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xds",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxds.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdt",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdt.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdu",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdu.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdv",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdv.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdw",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdw.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdx",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdx.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdy",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdy.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xdz",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxdz.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xea",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxea.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xeb",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxeb.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xec",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxec.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xed",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxed.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xee",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxee.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xef",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxef.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xeg",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxeg.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xeh",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxeh.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xei",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxei.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xej",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxej.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xek",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxek.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xel",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxel.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xem",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxem.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xen",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxen.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xeo",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxeo.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xep",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxep.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xeq",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxeq.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xer",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxer.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xes",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxes.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xet",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxet.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xeu",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxeu.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xev",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxev.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xew",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxew.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xex",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxex.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xey",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxey.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xez",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxez.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfa",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfa.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfb",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfb.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfc",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfc.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfd",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfd.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfe",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfe.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xff",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxff.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfg",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfg.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfh",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfh.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfi",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfi.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfj",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfj.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfk",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfk.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfl",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfl.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfm",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfm.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfn",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfn.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfo",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfo.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfp",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfp.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfq",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfq.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfr",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfr.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xfs",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxfs.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
yy <- read.csv("xft",header=FALSE)
str(yy)
system.time(r3 <- TPL(yy$V1[1:800], corr=TRUE, diffchar = 2, max.distance = 2))
str(r3)
write.table(r3,file="outxft.csv",sep=",",row.names = FALSE, col.names = FALSE)
warnings()
rm(r3)
rm(yy)
